- id: '1611982176739'
  alias: System / LetsEncrypt - Cert Renewal
  description: ''
  trigger:
  - at: 00:02
    platform: time
  condition: []
  action:
  - data:
      addon: core_letsencrypt
    service: hassio.addon_restart
  mode: single
- id: '1612291452533'
  alias: Shed / Grow Light / ON - Sunrise
  description: ''
  trigger:
  - platform: sun
    event: sunrise
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.plg_utility
  mode: single
- id: '1612291484467'
  alias: Shed / Grow Light / OFF - after 8 hrs
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 08:00:00
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.plg_utility
  mode: single
- id: '1612291548796'
  alias: Shed / Fan / ON - Hrly cycle
  description: ''
  trigger:
  - hours: /1
    platform: time_pattern
  condition:
  - condition: state
    entity_id: switch.sw_shedfan
    state: 'off'
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.sw_shedfan
  - delay: 00:10:00
  - service: switch.turn_off
    data: {}
    entity_id: switch.sw_shedfan
  mode: single
- id: '1612292614712'
  alias: Kitchen / Speaker / ON - music playing
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.kitchen_speaker
    to: playing
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.plg_kitchenspeaker
  mode: single
- id: '1612292752882'
  alias: Kitchen / Speaker / OFF - music stops
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.kitchen_speaker
    from: playing
    to: idle
    for: 00:00:30
  - platform: state
    entity_id: media_player.kitchen_speaker
    to: 'off'
  condition:
  - condition: state
    entity_id: switch.plg_kitchenspeaker
    state: 'on'
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.plg_kitchenspeaker
  mode: single
- id: '1612292819059'
  alias: Kitchen / Sink / ON - @ Sunset
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition:
  - condition: state
    entity_id: switch.sw_kitchensink
    state: 'off'
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.sw_kitchensink
  mode: single
- id: '1612292887886'
  alias: Kitchen / Sink / OFF - @ 01:00
  description: ''
  trigger:
  - platform: time
    at: 01:01
  condition:
  - condition: state
    entity_id: switch.sw_kitchensink
    state: 'on'
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.sw_kitchensink
  mode: single
- id: '1612294990194'
  alias: Driveway / Lights / ON - @ Sunset
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 00:15:00
  condition:
  - condition: state
    entity_id: switch.sw_driveway
    state: 'off'
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.sw_driveway
  mode: single
- id: '1612295061627'
  alias: Driveway / Lights / OFF - @ Sunrise
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: -00:15:00
  condition:
  - condition: state
    entity_id: switch.sw_driveway
    state: 'on'
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.sw_driveway
  mode: single
- id: '1612295242635'
  alias: Outside / Outlet / ON - Holiday Schedule
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition:
  - condition: state
    entity_id: switch.sw_fronthouseoutlet
    state: 'off'
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.sw_fronthouseoutlet
  mode: single
- id: '1612295307179'
  alias: Outside / Outlet / OFF - Holiday Schedule
  description: ''
  trigger:
  - platform: time
    at: '22:30'
  condition:
  - condition: state
    entity_id: switch.sw_fronthouseoutlet
    state: 'on'
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.sw_fronthouseoutlet
  mode: single
- id: '1612298561421'
  alias: Main Bedroom / Heater / OFF - morning
  description: ''
  trigger:
  - platform: time
    at: 05:30
  condition:
  - condition: state
    entity_id: switch.plg_mainbedroom1
    state: 'on'
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.plg_mainbedroom1
  mode: single
- id: '1612299207142'
  alias: Main Bedroom / Heater / ON
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: and
    conditions:
    - condition: numeric_state
      below: '21.6'
      entity_id: sensor.snr_mainbedroomclimate_temperature
    - condition: time
      after: '21:00'
      before: 05:29
    - condition: state
      entity_id: switch.plg_mainbedroom1
      state: 'off'
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.plg_mainbedroom1
  mode: single
- id: '1612306243899'
  alias: Garage / Lights / ON - door opened @ night
  description: ''
  trigger:
  - platform: state
    from: 'off'
    to: 'on'
    entity_id: binary_sensor.snr_garagedoorhousecontact_contact
  - platform: state
    entity_id: binary_sensor.snr_garagedoorsidecontact_contact
    from: 'off'
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: sun.sun
      state: below_horizon
    - condition: state
      entity_id: switch.sw_garageceilingmain
      state: 'off'
      for: 00:00:10
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.sw_garageceilingmain
  mode: single
- id: '1612309818757'
  alias: Garage / Side / ON - Motion @ night
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.wyzesense_77a7a16f
    from: 'off'
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: sun.sun
      state: below_horizon
    - condition: state
      entity_id: switch.sw_garagesidedoor
      state: 'off'
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.sw_garagesidedoor
  - wait_for_trigger:
    - platform: state
      entity_id: binary_sensor.wyzesense_77a7a16f
      from: 'on'
      to: 'off'
  - delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    data: {}
    entity_id: switch.sw_garagesidedoor
  mode: restart
- id: '1612312535434'
  alias: Porch / Lights / ON - Motion
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.wyzesense_77a7a12e
    from: 'off'
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: sun.sun
      state: below_horizon
    - condition: state
      entity_id: switch.sw_porch
      state: 'off'
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.sw_porch
  - wait_for_trigger:
    - platform: state
      entity_id: binary_sensor.wyzesense_77a7a12e
      from: 'on'
      to: 'off'
  - delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    data: {}
    entity_id: switch.sw_porch
  mode: restart
- id: '1612462343806'
  alias: Garage / Dehumidifier / OFF - Door Open
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.wyzesense_77a05475
    from: 'off'
    to: 'on'
    for: 00:00:20
  condition:
  - condition: state
    entity_id: switch.plg_garagedehumidifier
    state: 'on'
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.plg_garagedehumidifier
  mode: single
- id: '1612462859674'
  alias: Garage / Dehumidifier / Check - door closes
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.wyzesense_77a05475
    from: 'on'
    to: 'off'
    for: 00:00:20
  condition:
  - condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.garage_humidity_int
      above: '65'
    - condition: state
      entity_id: switch.plg_garagedehumidifier
      state: 'off'
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.plg_garagedehumidifier
  mode: single
- id: '1612463000537'
  alias: Garage / Dehumidifier / ON - High Humidity
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.garage_humidity_int
    above: '65'
    for: 00:05:00
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: switch.plg_garagedehumidifier
      state: 'off'
    - condition: state
      entity_id: binary_sensor.wyzesense_77a05475
      state: 'off'
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.plg_garagedehumidifier
  mode: single
- id: '1612463100433'
  alias: Garage / Dehumidifier / OFF - Low Humidity
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.garage_humidity_int
    for: 00:15:00
    below: '61'
  condition:
  - condition: state
    entity_id: switch.plg_garagedehumidifier
    state: 'on'
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.plg_garagedehumidifier
  mode: single
- id: '1612671461820'
  alias: (TESTING) Ikea Light Disco
  description: ''
  trigger:
  - platform: time_pattern
    seconds: /5
  condition: []
  action:
  - service: light.turn_on
    data:
      hs_color:
      - '{{ range(360) | random }}'
      - '{{ range(80,101) | random }}'
      brightness_pct: 100
      transition: 1
    entity_id: light.lgt_kidsroom1
  mode: single
- id: '1612673570521'
  alias: (Testing) IKEA button press (right click)
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.sw_kidsroomremote_action
    to: arrow_right_click
  condition: []
  action:
  - service: light.turn_on
    data:
      hs_color:
      - '{{ range(360) | random }}'
      - '{{ range(80,101) | random }}'
      brightness_pct: 100
      transition: 1
    entity_id: light.kids_bedroom_lights
  mode: single
- id: '1612674226139'
  alias: (Testing) IKEA button press (toggle)
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.sw_kidsroomremote_action
    to: toggle
  condition: []
  action:
  - service: light.toggle
    entity_id: light.kids_bedroom_lights
  mode: single
- id: '1612674480083'
  alias: (Testing) IKEA button press (left arrow)
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.sw_kidsroomremote_action
    to: arrow_left_click
  condition: []
  action:
  - service: light.turn_on
    data:
      rgb_color:
      - 255
      - 196
      - 137
      transition: 1
    entity_id: light.kids_bedroom_lights
  mode: single
- id: '1612674611182'
  alias: (Testing) IKEA button press (down arrow)
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.sw_kidsroomremote_action
    to: brightness_down_click
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_step_pct: -20
      transition: 1
    entity_id: light.kids_bedroom_lights
  mode: single
- id: '1612674710463'
  alias: (Testing) IKEA button press (up arrow)
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.sw_kidsroomremote_action
    to: brightness_up_click
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_step_pct: 20
      transition: 1
    entity_id: light.kids_bedroom_lights
  mode: single
- id: '1613012241426'
  alias: Office / Air Purifier / ON - with occupancy
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.snr_officemotion_occupancy
    from: 'off'
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: time
      after: 08:00
      before: '22:00'
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun
    - condition: state
      entity_id: switch.plg_officeairpurifier
      state: 'off'
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.plg_officeairpurifier
  mode: restart
- id: '1613012339822'
  alias: Office / Air Purifier / OFF
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.snr_officemotion_occupancy
    to: 'off'
    for: 00:10:00
  condition:
  - condition: and
    conditions:
    - condition: time
      after: 08:00
      before: '22:30'
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun
    - condition: state
      entity_id: switch.plg_officeairpurifier
      state: 'on'
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.plg_officeairpurifier
  mode: single
- id: '1613958937211'
  alias: House / Leak / Alert - critical notification
  description: ''
  mode: single
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.snr_dishwasherleak_water_leak
    - binary_sensor.snr_downtoiletleak_water_leak
    - binary_sensor.snr_ensuitebathtubleak_water_leak
    - binary_sensor.snr_ensuitetoiletleak_water_leak
    - binary_sensor.snr_espressoleak_water_leak
    - binary_sensor.snr_fridgeleak_water_leak
    - binary_sensor.snr_hotwatertankleak_water_leak
    - binary_sensor.snr_laundryleak_water_leak
    - binary_sensor.snr_upcommontoiletleak_water_leak
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_turraphone
    data:
      title: ‚ùóüíß Water Detected
      message: '"Water detected at {{ trigger.to_state.attributes.friendly_name }}
        sensor."'
      data:
        push:
          sound:
            name: default
            critical: 1
            volume: 1
  - repeat:
      count: '3'
      sequence:
      - service: script.sonos_say
        data:
          sonos_entity:
          - media_player.family_room
          - media_player.main_bedroom
          volume: 0.8
          message: '"ALERT. Water detected at {{ trigger.to_state.attributes.friendly_name
            }} sensor."'
          delay: 00:00:07
- id: '1616274628046'
  alias: Kitchen / Espresso / ON - morning
  description: turn on the espresso machine in the morning (between 05:00 - 10:00)
    when chris' iphone is removed from the charger for 1 minute.
  trigger:
  - platform: state
    entity_id: sensor.turraphone_battery_state
    to: Not Charging
    for: 00:01:00
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: device_tracker.turraphone
      state: home
    - condition: time
      before: '10:00'
      after: 05:00
    - condition: state
      entity_id: switch.plg_espressomachine
      state: 'off'
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.plg_espressomachine
  mode: single
- id: '1616875296550'
  alias: Crawlspace / Locker / Open - alert
  description: when locker door is opened notify chris' iphone.
  trigger:
  - platform: state
    entity_id: binary_sensor.snr_lockercontact_contact
    to: 'on'
    for: 00:00:02
  condition: []
  action:
  - service: notify.mobile_app_turraphone
    data:
      title: ‚ùóüö™ Locker Door Open
      message: Locker Door has been opened
      data:
        push:
          sound:
            name: default
            critical: 1
            volume: 1
  mode: single
- id: '1617333806988'
  alias: Shed / Flood / ON - motion @ night
  description: turn on shed flood light 15 minutes after sun is below the horizon
    and keep on for 5 minutes after motion is no longer detected.
  trigger:
  - platform: state
    to: 'on'
    entity_id: binary_sensor.snr_shedoutsidemotion_occupancy
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: sun.sun
      state: below_horizon
      for: 00:15:00
    - condition: state
      entity_id: switch.sw_shedflood
      state: 'off'
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.sw_shedflood
  - wait_for_trigger:
    - platform: state
      entity_id: binary_sensor.snr_shedoutsidemotion_occupancy
      from: 'on'
      to: 'off'
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    data: {}
    entity_id: switch.sw_shedflood
  mode: restart
- id: '1618634466675'
  alias: Yard / Motion / ON - at night
  description: turn on porch lights in motion is detected in front yard at night
  trigger:
  - platform: state
    entity_id: binary_sensor.wyzesense_779f1f3a
    from: 'off'
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: time
      after: 00:30
      before: 06:00
    - condition: state
      entity_id: switch.sw_porch
      state: 'off'
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.sw_porch
  - wait_for_trigger:
    - platform: state
      from: 'on'
      to: 'off'
      entity_id: binary_sensor.wyzesense_779f1f3a
  - delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    data: {}
    entity_id: switch.sw_porch
  mode: restart
- id: '1619640982634'
  alias: Shed / Door / ON - notify @ night
  description: notify chris' phone if the shed door is left open for 5 minutes when
    the time is after 22:30.
  trigger:
  - platform: time_pattern
    minutes: /10
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: binary_sensor.snr_sheddoorcontact_contact
      state: 'on'
      for: 00:05:00
    - condition: time
      after: '22:30'
  action:
  - service: notify.mobile_app_turraphone
    data:
      message: Shed Door has been left open
      title: ‚ùóüö™ Shed Door Open
      data:
        push:
          sound:
            name: default
            critical: 1
            volume: 1
  mode: single
- id: '1619814582936'
  alias: Shed / Fan / ON - cycle when door opened
  description: turn on shed exhaust fan for 10 minutes when the door is opened.
  trigger:
  - platform: state
    entity_id: binary_sensor.snr_sheddoorcontact_contact
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.sw_shedfan
    state: 'off'
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.sw_shedfan
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    target:
      entity_id: switch.sw_shedfan
  mode: single
- id: '1620159763993'
  alias: Shed / Fan / ON - cycle when door open
  description: cycle fan on for 10 min every 30 min when the shed door is open.
  trigger:
  - platform: time_pattern
    minutes: /30
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: binary_sensor.snr_sheddoorcontact_contact
      state: 'on'
    - condition: state
      entity_id: switch.sw_shedfan
      state: 'off'
      for: 00:10:00
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.sw_shedfan
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    target:
      entity_id: switch.sw_shedfan
  mode: single
